### ISSUE TITLE
How do I make packer-produced images on private Triton "public"?

### ISSUE THREAD

**Issue by curiositycasualty** [joyent/packer-builder-triton#10]
I noticed there's a `image_acls` options, but it's unclear what to use for it.
Is there a special UUID that represents all users?

I noticed that the `create-from-vm` endpoint when called directly via `sdc-imgapi` on the headnode includes a "public: true" option.
How do I achieve the same with my packer triton build?

**Comment by dfredell** [comment]
I was working on code for this and discovered this is a dead repo. The code is actually at https://github.com/hashicorp/packer/tree/master/builder/triton

**Comment by curiositycasualty** [comment]
Closing own stale issues.
