### ISSUE TITLE
Detect 409 Conflict if named source machine already exists

### ISSUE THREAD

**Issue by jen20** [joyent/packer-builder-triton#2]
Originally it appeared that SDC would assign a name to a source machine if none was specified - this appears to no longer be the case, so we should detect errors of this form in order to present a friendlier message to users:

```
Build 'triton' errored: Problem creating source machine: failed to create machine with name: testbuild_1
caused by: Missing parameters https://us-east-1.api.joyent.com/EventStore/machines
caused by: request "https://us-east-1.api.joyent.com/EventStore/machines" returned unexpected status 409 with body "{\"code\":\"ValidationFailed\",\"message\":\"Invalid VM parameters: Invalid machine name\",\"errors\":[{\"field\":\"alias\",\"code\":\"Duplicate\",\"message\":\"Already exists for this owner_uuid\"}]}"
```

**Comment by misterbisson** [comment]
@jen20: This repo has gone stale, but you already know that ;-). I'm closing this issue so we can continue work in https://github.com/mitchellh/packer/pull/3441.
