### ISSUE TITLE
triton insecure: true not allowing packer builds.

### ISSUE THREAD

**Issue by Smithx10** [joyent/packer-builder-triton#7]
While using the following triton profile triton builds don't work.

[bsmith@arch01 ~]$ cat .triton/profiles.d/tfh-east-1.json 
{
    "url": "https://10.88.88.5",
    "account": "bsmith",
    "keyId": "insertkeyidhere",
    "insecure": true
}

Packer File:
[bsmith@arch01 coding]$ cat test.json 
{
    "variables": {
        "triton_url": "{{env `SDC_URL`}}",
        "triton_account": "{{env `SDC_ACCOUNT`}}",
        "triton_key_id": "{{env `SDC_KEY_ID`}}",
        "triton_key_material": "{{env `SDC_KEY_MATERIAL`}}"
    },

```
"builders": [
    {
        "type": "triton",
        "triton_url": "{{user `triton_url`}}",
        "triton_account": "{{user `triton_account`}}",
        "triton_key_id": "{{user `triton_key_id`}}",
        "triton_key_material": "{{user `triton_key_material`}}",

        "source_machine_package": "docker_2048",
    "source_machine_name": "test-01",
        "source_machine_image": "842e6fa6-6e9b-11e5-8402-1b490459e334",
        "source_machine_networks": [
            "56537765-b450-4a8e-8b51-113924bf0c25"
        ],
        "source_machine_metadata": {
            "Key1": "Value1"
        },
        "source_machine_tags": {
            "Project": "Packer-Triton"
        },
        "source_machine_firewall_enabled": false,

        "image_name": "my-test-image",
        "image_version": "1.0.0",
        "image_description": "SDC Image created with Packer",
        "image_homepage": "http://jen20.com",
        "image_eula_url": "https://www.mozilla.org/media/MPL/2.0/index.815ca599c9df.txt",
        "image_acls": [],
        "image_tags": {
            "Project": "Packer-Triton"
        }
    }
],

"provisioners": [
    {
        "type": "shell",
        "inline": ["touch foo.txt"]
    }
]
```

}

[bsmith@arch01 coding]$ packer validate test.json 
Template validated successfully.

[bsmith@arch01 coding]$ packer build test.json 
triton output will be in this color.

==> triton: Creating source machine...
Build 'triton' errored: Problem creating source machine: failed to create machine with name: test-01
caused by: failed executing the request https://10.88.88.5/bsmith/machines
caused by: Post https://10.88.88.5/bsmith/machines: x509: cannot validate certificate for 10.88.88.5 because it doesn't contain any IP SANs

==> Some builds didn't complete successfully and had errors:
--> triton: Problem creating source machine: failed to create machine with name: test-01
caused by: failed executing the request https://10.88.88.5/bsmith/machines
caused by: Post https://10.88.88.5/bsmith/machines: x509: cannot validate certificate for 10.88.88.5 because it doesn't contain any IP SANs

==> Builds finished but no artifacts were created.

It seems the packer builder doesn't support insecure.

**Comment by misterbisson** [comment]
@Smithx10: This repo has gone stale. The most current code is PR'd against origin in https://github.com/mitchellh/packer/pull/3441. Please try building that branch/pr and submit any feedback on that pr.
